### ISSUE TITLE
Shaunting Yard  Algorithm

### ISSUE THREAD

**Issue by deepakbhagat7** [ahmedivy/data-structures#3]
Here is how the algorithm works:

Create an empty stack for operators and an empty queue for output.
Read the expression from left to right.
If the token is a number, add it to the output queue.
If the token is an operator, then:
a. While there is an operator on top of the operator stack with greater or equal precedence and it is not a left parenthesis, pop it off the stack and add it to the output queue.
b. Push the current operator onto the operator stack.
If the token is a left parenthesis, push it onto the operator stack.
If the token is a right parenthesis, then:
a. While the top of the operator stack is not a left parenthesis, pop operators off the stack and add them to the output queue.
b. Pop the left parenthesis off the operator stack (and discard it).
When there are no more tokens to read, pop any remaining operators off the stack and add them to the output queue.
The output queue now contains the postfix notation of the input expression.

can I write the code for it??

**Comment by ahmedivy** [comment]
I already implemented this [here](https://github.com/ahmedivy/data-structures/blob/main/stack/applications/shunting-yard.cpp), but it might have some issues, if you can fix it, then open pull request and I will merge it.

**Comment by ahmedivy** [comment]
It worked well and it also worked on 2 or more digit numbers, untill you provide a space between operands and operators. Only problem is that while printing answer it does not take care of spaces. For Example,
for this infix expression : (10 + 20) * 30 - 40 / 50 ^ 60
it will output this: 1020+30*405060^/-
instead it should take care of spaces and print: 10 20 + 30 * 40 50 60 ^ / -

If you can
